# Generated by Django 4.1.3 on 2022-11-28 15:00

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position1', models.CharField(max_length=255)),
                ('position2', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('saque', models.IntegerField(default=0)),
                ('recepcion', models.IntegerField(default=0)),
                ('dedos', models.IntegerField(default=0)),
                ('dedos_doble', models.IntegerField(default=0)),
                ('ataque', models.IntegerField(default=0)),
                ('foto', models.ImageField(default='static/assets/fondo.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(max_length=255)),
                ('status', models.CharField(choices=[('En preparacion', 'En preparacion'), ('Espera', 'Espera'), ('Listo', 'Listo')], default='En preparacion', max_length=255)),
                ('num_max_players', models.IntegerField()),
                ('num_players', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_num_players', models.IntegerField()),
                ('num_players', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volley_team_maker.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('estadisticas_jugador', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='volley_team_maker.estadisticasjugador')),
                ('name', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255)),
                ('max_num_players', models.IntegerField(default=1)),
                ('num_players', models.IntegerField(default=1)),
                ('genero', models.CharField(max_length=255)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volley_team_maker.equipo')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volley_team_maker.partido')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Normal')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volley_team_maker.jugador')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
