# Generated by Django 3.2.8 on 2026-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volley_team_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='max_num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(default='2012-12-31', max_length=255),
        ),
        migrations.AlterField(
            model_name='partido',
            name='num_max_players',
            field=models.IntegerField(default=0),
        ),
    ]
